config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end

  devise_for :users
  
  

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	validates :title, presence: true, uniqueness: true
	validates :body, presence: true, length: { minimum: 20 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  belongs_to :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:show,:index]
	#GET /articles
	def index
		@articles = Article.all.order(created_at: :desc)
	end

	#GET /articles:id
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
	end

	#GET /articles/new
	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end
	#POST /articles
	def create
		@article = current_user.articles.new(article_params)

		if @article.save
			redirect_to @article
		else
			render :new
		end		
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end
	end

	private

	def article_params
		params.require(:article).permit(:title,:body)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_article
    @article = Article.find(params[:article_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% name ||= "Error declara la variable name"%>
<h1><%= name %></h1>
<%= form_for(@article) do |f| %>
	<% @article.errors.full_messages.each do |message| %>
		<div class="error-form">
			<%=message%>
		</div>
	<%end%>
	<div>
		<%= f.text_field :title, id: "input-title" %>
		<label for="" class="title-input">Titulo del articulo</label>
	</div>
	<div>
		<%= f.text_area :body, id: "input-body" %>
		<label for="" class="title-input">Escribe aqui el articulo</label>
	</div>
	<div>
		<%= f.submit "Guardar", id: "input-boton"%>
	</div>
<%end%>

app/views/articles/edit.html.erb
<div id="wrapper-new">
	<%= render "form", name: "Editar articulo" %>
</div>

app/views/articles/index.html.erb
<article id="wrapper-main-blog">
	<% @articles.each do |article|%>
	 	<div class="wrapper-article">
			<h3 class="title-article"><%= link_to article.title, controller: "articles", action: "show", id: article%></h3>
			<div class="body-article"><%= truncate(article.body, :length => 150)%></div>
			<div class="boton-leerMas">
				
			</div>
		</div>
	<%end%>
</article>

app/views/articles/new.html.erb
<div id="wrapper-new">
	<%= render "form", name: "Nuevo articulo" %>
</div>

app/views/articles/show.html.erb
<div class="background-show-title">
	<h3 class="title-show"><%= @article.title %></h3>
	<% unless @article.user.nil? %>
		<p class="user-show">Escrito por: <%= @article.user.email %></p>

	<%end%>
	<%= link_to "editar", edit_article_path(@article) %>
</div>
<div id="wrapper-post-show">
	<div class="body-show"><%= @article.body %></div>
</div>
<div>
	<h3>Comentarios</h3>
	<%= render "comments/form" %>
	<ul>
		<% @article.comments.each do |comment| %>
			<li>
				<%= comment.body %> - <%= comment.user.email %>
			</li>
		<%end%>
	</ul>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GENIAL BLOG</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="notice_wrapper">
	  <% if notice %>
	     <p class="notice"><%= notice %></p>
	  <% elsif alert %>  
	     <p class="alert"><%= alert %></p>
	  <% end %>   
	</div>
	
	<%= render "partials/navigation" %>

	<%= yield %>

</body>
</html>

app/views/partials/_navigation.html.erb
<header>
	<div id="wrapper-header">
		<%= link_to image_tag("logo.png"), articles_path %>
		<% if user_signed_in? %>
			<div><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %></div>
			<div class="user-nav"><%= current_user.email %></div>
		<%else%>
			<div><%= link_to "Iniciar sesion", new_user_session_path %></div>
			<div><%= link_to "Crear cuenta", new_user_registration_path %></div>
		<%end%>
	</div>
</header>

app/views/welcome/index.html.erb
<h1>hola</h1>
<p>Bienvenidos al blog :D</p>